import { Card, Col, List, Progress, Row, Space, Statistic, Table, Tag, Typography } from 'antd';
import { auditItems } from '../data/demoData';

const risks = [{ state: 'BLOCKED', content: '敏感学生身份字段外发请求已拦截', time: '10:31:04' }, { state: 'MANUAL_REVIEW', content: '实验 Prompt 等待教研负责人审核', time: '09:48:29' }, { state: 'FAILED', content: '模拟模型超时任务，未伪装为成功', time: '09:14:02' }];
export function SecurityOperations() {
  return <div className="page"><div className="page-heading"><div><Typography.Title level={2}>安全运营中心</Typography.Title><Typography.Text type="secondary">模型、Agent、数据策略、风险和审计的统一观察面</Typography.Text></div><Tag color="red">SECURITY OPS</Tag></div>
    <Row gutter={[16, 16]}><Col xs={12} lg={6}><Card><Statistic title="今日 AI 调用" value={46} /></Card></Col><Col xs={12} lg={6}><Card><Statistic title="策略拦截" value={3} valueStyle={{ color: '#d84a3a' }} /></Card></Col><Col xs={12} lg={6}><Card><Statistic title="待人工复核" value={2} valueStyle={{ color: '#d9780e' }} /></Card></Col><Col xs={12} lg={6}><Card><Statistic title="Trace 完整率" value={100} suffix="%" valueStyle={{ color: '#1f9d72' }} /></Card></Col></Row>
    <Row gutter={[20, 20]} className="top-gap"><Col xs={24} lg={14}><Card title="模型调用监控"><Row gutter={16}><Col span={12}><Typography.Text type="secondary">Local Model v1.3</Typography.Text><Typography.Title level={3}>38</Typography.Title><Progress percent={83} showInfo={false} strokeColor="#1f9d72" /></Col><Col span={12}><Typography.Text type="secondary">DeepSeek（受控展示）</Typography.Text><Typography.Title level={3}>8</Typography.Title><Progress percent={17} showInfo={false} strokeColor="#5e79da" /></Col></Row><Space className="top-gap-small"><Tag>平均耗时 1.2s</Tag><Tag>外发策略：默认禁止</Tag></Space></Card></Col><Col xs={24} lg={10}><Card title="风险事件"><List dataSource={risks} renderItem={(item) => <List.Item><Space><Tag color={item.state === 'FAILED' ? 'red' : item.state === 'BLOCKED' ? 'volcano' : 'gold'}>{item.state}</Tag><span>{item.content}</span></Space><Typography.Text type="secondary">{item.time}</Typography.Text></List.Item>} /></Card></Col></Row>
    <Card className="top-gap" title="Audit / Trace 查询结果"><Table rowKey="time" scroll={{ x: 680 }} pagination={false} dataSource={auditItems} columns={[{ title: 'Trace', render: () => <Typography.Text code>trc_8f61…</Typography.Text> }, { title: '主体', dataIndex: 'actor' }, { title: '操作', dataIndex: 'action' }, { title: '结果', dataIndex: 'result' }, { title: '时间', dataIndex: 'time' }]} /></Card>
  </div>;
}
